
project_id = "zzbftruhrjfmynhamypk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.twitter-historical]
verify_jwt = false

[functions.setup-tweet-cron]
verify_jwt = false

[functions.scheduled-tweet-fetch]
verify_jwt = false
