
project_id = "zzbftruhrjfmynhamypk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true

[realtime]
enabled = true

[[functions]]
name = "twitter-historical"
verify_jwt = false
